# Generated by Django 2.2.4 on 2019-08-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='exaplanation',
            field=models.TextField(blank=True),
        ),
    ]
