# Generated by Django 2.2.4 on 2019-08-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_condition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
