# Generated by Django 2.2.4 on 2019-08-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20190819_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='slug',
        ),
    ]
