# Generated by Django 2.2.4 on 2019-08-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_remove_condition_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='exaplanation',
            new_name='explanation',
        ),
    ]
