# Generated by Django 2.2.4 on 2019-08-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20190819_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_language', models.CharField(choices=[('Python', 'PYTHON')], default='Python', max_length=20)),
                ('code_itself', models.TextField()),
            ],
        ),
    ]
