# Generated by Django 2.2.4 on 2019-08-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_auto_20190821_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_language',
            field=models.CharField(choices=[('5', 'Python')], default='Python', max_length=20),
        ),
    ]
