# Generated by Django 2.2.4 on 2019-08-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20190821_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_language',
            field=models.CharField(choices=[('5', 'Python'), ('1', 'C#')], default='Python', max_length=20),
        ),
    ]
