# Generated by Django 2.2.3 on 2019-07-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_information',
            field=models.URLField(default=''),
        ),
    ]
