# Generated by Django 2.1.3 on 2019-06-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190627_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='solved_problems',
            field=models.IntegerField(default=0),
        ),
    ]
