# Generated by Django 2.1.3 on 2019-06-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
